FROM fedora

COPY *.py *.txt *.sh *.ini /app/

RUN dnf update -y && dnf install -y postgresql python3 python3-pip libpq-devel gcc python3-devel python3-requests && cd /app && pip3 install -r requirements.txt

CMD /app/start.sh
